const fs=require('fs'),{chromium}=require('./runtime.cjs')('playwright');const R=__dirname,U='http://127.0.0.1:8769';
(async()=>{const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{channel:'chrome'}),headless:true}),page=await browser.newPage({viewport:{width:1500,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(U+'/previews/preview.html');await page.waitForFunction(()=>window.previewReady===true);
const states=[];for(const name of['原图睁眼','轻闭','近闭','全闭']){await page.getByRole('button',{name,exact:true}).click();states.push({name,status:await page.locator('#status').textContent()});await page.locator('#zoom').screenshot({path:R+'/qa/browser-eyes-'+states.length+'.png'});}
await page.screenshot({path:R+'/qa/browser-preview.png',fullPage:true});
await page.locator('#openness').fill('20');await page.locator('#openness').dispatchEvent('input');const slider=await page.locator('#openvalue').textContent();
await page.getByRole('button',{name:'下一帧',exact:true}).click();const step=await page.locator('#status').textContent();
await page.locator('#scrub').fill('1000');await page.locator('#scrub').dispatchEvent('input');await page.locator('#play').click();
const live=await page.evaluate(()=>new Promise(resolve=>{const seen=new Set(),start=performance.now();function tick(){const a=document.getElementById('native').getContext('2d').getImageData(210,195,88,44).data;let h=2166136261;for(const v of a)h=Math.imul(h^v,16777619);seen.add(h>>>0);if(performance.now()-start>=4300)resolve({uniqueFrames:seen.size,elapsedMs:performance.now()-start});else requestAnimationFrame(tick)}tick()}));
await page.goto(U+'/previews/blink-normal.svg');await page.waitForFunction(()=>document.querySelectorAll('image').length===17);await page.evaluate(async()=>{await Promise.all(Array.from(document.querySelectorAll('image')).map(e=>new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=reject;i.src=e.getAttribute('href')})));document.documentElement.pauseAnimations()});
const svg=[];for(const sec of[.5,1.01,1.07,1.1,1.15,1.25,1.31,3.99,4.01]){const active=await page.evaluate(sec=>{document.documentElement.setCurrentTime(sec);return Array.from(document.querySelectorAll('image')).filter(e=>+getComputedStyle(e).opacity>.5).map(e=>e.id)},sec);svg.push({seconds:sec,active});if(sec===1.1)await page.locator('svg').screenshot({path:R+'/qa/svg-closed.png',omitBackground:true});}
await page.evaluate(()=>document.documentElement.unpauseAnimations());const svgLive=await page.evaluate(()=>new Promise(resolve=>{const seen=new Set(),start=performance.now();function tick(){seen.add(Array.from(document.querySelectorAll('image')).filter(e=>+getComputedStyle(e).opacity>.5).map(e=>e.id).join(','));if(performance.now()-start>=4300)resolve({uniqueFrames:seen.size});else requestAnimationFrame(tick)}tick()}));
await page.goto(U+'/qa/encoded-playback.html');await page.evaluate(()=>Promise.all(['webp','gif'].map(id=>document.getElementById(id).decode())));const seen={webp:new Set(),gif:new Set()},startTime=Date.now(),sharp=require('./runtime.cjs')('sharp'),crypto=require('crypto');let samples=0;while(Date.now()-startTime<4600){const shot=await page.screenshot({clip:{x:210,y:195,width:600,height:44}});for(const [id,left]of[['webp',0],['gif',512]]){const pixels=await sharp(shot).extract({left,top:0,width:88,height:44}).raw().toBuffer();seen[id].add(crypto.createHash('sha256').update(pixels).digest('hex'));}samples++;}const encodedLive={webpUniqueFrames:seen.webp.size,gifUniqueFrames:seen.gif.size,screenshotSamples:samples,method:'Actual painted animated image screenshots; canvas drawImage uses the default animation frame'};await browser.close();
const report={browser:'Chrome headless, isolated profile',errors,states,slider,step,live,svg,svgLive,encodedLive};report.pass=errors.length===0&&states.every(s=>s.status===s.name)&&slider==='50.0%'&&step.includes('第')&&live.uniqueFrames>5&&svg.every(s=>s.active.length===1)&&svgLive.uniqueFrames>5&&encodedLive.webpUniqueFrames>2&&encodedLive.gifUniqueFrames>2;fs.writeFileSync(R+'/qa/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
