const fs=require('fs'),crypto=require('crypto'),sharp=require('./runtime.cjs')('sharp');const R=__dirname;
(async()=>{const base=await sharp(R+'/source/idle.alt.png').ensureAlpha().raw().toBuffer(),clean=await sharp(R+'/layers/face-clean.png').ensureAlpha().raw().toBuffer(),closed=await sharp(R+'/frames/closed.png').ensureAlpha().raw().toBuffer(),mask=await sharp(R+'/layers/edit-mask.png').ensureAlpha().raw().toBuffer(),line=Buffer.alloc(base.length);
for(let j=0;j<512*512;j++)if(mask[j*4+3]&&[0,1,2].some(c=>closed[j*4+c]!==clean[j*4+c]))closed.copy(line,j*4,j*4,j*4+4);
await sharp(line,{raw:{width:512,height:512,channels:4}}).png().toFile(R+'/layers/closed-eyeline-baked-edge.png');
const metrics=[];for(const p of[.005,.015,.05,.12]){const b=await sharp(R+'/qa/p-'+p+'.png').ensureAlpha().raw().toBuffer();let max=0,total=0,count=0;for(let j=0;j<512*512;j++)if(mask[j*4+3])for(let c=0;c<3;c++){const d=Math.abs(b[j*4+c]-base[j*4+c]);max=Math.max(max,d);total+=d;count++;}metrics.push({close:p,meanAbsChannelChangeInsideMask:total/count,maxChannelChange:max});}
const pixels=JSON.parse(fs.readFileSync(R+'/qa/verification.json')),browser=JSON.parse(fs.readFileSync(R+'/qa/browser-report.json')),geometry=JSON.parse(fs.readFileSync(R+'/qa/initial-report.json'));
const report={status:'completed-preview-revision',pixelValidation:pixels.pass,browserValidation:browser.pass,geometryValidation:geometry.geometry.every(e=>e.minGap>=-1e-9&&e.nonmonotonic===0),visualReview:{reviewer:'assistant',views:['four-state eye zoom','micro-close states 0.5/1.5/5/12 percent','12 continuous eye states','276px full-body light/dark','browser closed screenshot'],observations:['First pass exposed upper lash soft-edge remnants; expanded cleanup support from 2 to 3.5 px and rechecked.','Current closed state has one shallow line per eye and no visible pupil remnant.','No apparent glasses jump or body motion in sampled views.','Skin fill is a harmonic estimate of the unseen eyelid surface, not recovered ground truth.']},microOpening:metrics,scope:{runtimeChanged:false,formalAssetsChanged:false,githubPushed:false,nativeCubismModel:false}};
if(!report.pixelValidation||!report.browserValidation||!report.geometryValidation)throw Error('Validation incomplete');
fs.writeFileSync(R+'/qa/acceptance.json',JSON.stringify(report,null,2));
const provenance={imageInputs:['source/idle.alt.png'],geometryInput:'source/calibration.json',sourceSha256:pixels.sourceSha256,method:'Original-image layers, fixed-position iris clipping, independently authored BD-local lid curves, source-sampled eyelash colour, harmonic skin completion, bounded keyform interpolation.',generativeModelUsed:false,oldBlinkArtworkUsed:false,oldMasksUsed:false,oldKeyformsUsed:false,tooling:'Node.js + sharp + isolated Chrome via Playwright',nearOpenCorrection:'A source-minus-open-model residual is attenuated only inside the edit mask over close 0..0.18, preserving exact rest and continuous micro-close; no whole-image crossfade.',closedLayer:'closed-eyeline-baked-edge.png includes the sampled clean-plate colour in soft edge pixels; composite only over face-clean.png.',timingFiles:['timing.json','timing-discrete.json'],displaySizeBasis:'MainWindow.xaml default width 300 and Viewbox margin 12 imply a 276px square canvas at default window size; OS DPI/user resizing may change physical pixels.'};
fs.writeFileSync(R+'/provenance.json',JSON.stringify(provenance,null,2));
const entries=[];for(const dir of['frames','layers','previews']){function walk(p){for(const f of fs.readdirSync(R+'/'+p,{withFileTypes:true})){const file=p+'/'+f.name;if(f.isDirectory())walk(file);else{const b=fs.readFileSync(R+'/'+file);entries.push({file,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')});}}}walk(dir);}
fs.writeFileSync(R+'/manifest.json',JSON.stringify({sourceSha256:pixels.sourceSha256,files:entries},null,2));console.log(JSON.stringify({accepted:report.status,files:entries.length,microOpening:metrics},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
