const fs=require('fs'),crypto=require('crypto'),sharp=require('./runtime.cjs')('sharp');const R=__dirname,N=512*512,bytes=N*4,hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const source=fs.readFileSync(R+'/source/idle.alt.png'),mother=fs.readFileSync(R+'/../../assets/sprites/idle.alt.png'),base=await sharp(source).ensureAlpha().raw().toBuffer(),mask=await sharp(R+'/layers/edit-mask.png').ensureAlpha().raw().toBuffer();
function pixel(b){let outside=0,alpha=0,changed=0;for(let j=0;j<N;j++){if(b[j*4+3]!==base[j*4+3])alpha++;if([0,1,2].some(c=>b[j*4+c]!==base[j*4+c])){changed++;if(!mask[j*4+3])outside++;}}return {outside,alpha,changed};}
const files=['frames/open.png','frames/light.png','frames/near.png','frames/closed.png',...fs.readdirSync(R+'/frames/slider').map(f=>'frames/slider/'+f),...fs.readdirSync(R+'/frames/sequence').map(f=>'frames/sequence/'+f)],png=[];
for(const file of files){const {data,info}=await sharp(R+'/'+file).ensureAlpha().raw().toBuffer({resolveWithObject:true});png.push({file,width:info.width,height:info.height,...pixel(data)});}
const timing=JSON.parse(fs.readFileSync(R+'/timing.json')),discrete=JSON.parse(fs.readFileSync(R+'/timing-discrete.json')),exports={};
for(const type of['normal','slow','discrete'])for(const ext of['webp','gif']){const file=R+'/previews/blink-'+type+'.'+ext,seq=(type==='discrete'?discrete:timing).sequence,factor=type==='slow'?4:1,m=await sharp(file,{animated:true}).metadata(),decoded=await sharp(file,{animated:true}).ensureAlpha().raw().toBuffer();let cursor=0,wrong=0,maxChannelError=0,alpha=0,outside=0;
if(ext==='webp'){for(let i=0;i<m.pages;i++){let c=0,index=0;for(let j=0;j<seq.length;j++){if(cursor<c+seq[j].ms*factor){index=j;break;}c+=seq[j].ms*factor;}const expected=await sharp(R+'/'+seq[index].file).ensureAlpha().raw().toBuffer(),page=decoded.subarray(i*bytes,(i+1)*bytes);for(let k=0;k<bytes;k++){if(page[k]!==expected[k])wrong++;maxChannelError=Math.max(maxChannelError,Math.abs(page[k]-expected[k]));}const p=pixel(page);alpha+=p.alpha;outside+=p.outside;cursor+=m.delay[i];}}
exports[type+'.'+ext]={pages:m.pages,width:m.width,pageHeight:m.pageHeight,loop:m.loop,delays:m.delay,totalMs:m.delay.reduce((a,b)=>a+b,0),hasAlpha:m.hasAlpha,...(ext==='webp'?{decodedWrongChannels:wrong,maxChannelError,outside,alpha}:{previewBackground:'#f2f0e9',pixelExact:false})};}
const first=await sharp(R+'/'+timing.sequence[0].file).raw().toBuffer(),last=await sharp(R+'/'+timing.sequence.at(-1).file).raw().toBuffer();
const clean=await sharp(R+'/layers/face-clean.png').ensureAlpha().raw().toBuffer(),reassembled=Buffer.from(clean);for(const id of['L','R']){const layer=await sharp(R+'/layers/eye-'+id+'-original.png').ensureAlpha().raw().toBuffer();for(let j=0;j<N;j++)if(layer[j*4+3])layer.copy(reassembled,j*4,j*4,j*4+4);}
const report={sourceByteIdentical:source.equals(mother),sourceSha256:hash(source),openByteIdentical:source.equals(fs.readFileSync(R+'/frames/open.png')),layerReassemblyMatchesSource:base.equals(reassembled),sequenceFirstLastIdentical:first.equals(last),png,exports,allPngOutsideZero:png.every(p=>p.outside===0),allPngAlphaZero:png.every(p=>p.alpha===0),allDimensions512:png.every(p=>p.width===512&&p.height===512)};
report.pass=report.sourceByteIdentical&&report.openByteIdentical&&report.layerReassemblyMatchesSource&&report.sequenceFirstLastIdentical&&report.allPngOutsideZero&&report.allPngAlphaZero&&report.allDimensions512&&Object.entries(exports).every(([k,v])=>v.totalMs===(k.startsWith('slow')?16000:4000)&&v.loop===0&&(!k.endsWith('webp')||v.decodedWrongChannels===0&&v.alpha===0&&v.outside===0));
fs.writeFileSync(R+'/qa/verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,png:'checked '+png.length+' PNG files'},null,2));if(!report.pass)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
