const fs=require('fs'),path=require('path'),crypto=require('crypto'),sharp=require('./runtime.cjs')('sharp');
const R=__dirname,W=512,N=W*W;
const cal=JSON.parse(fs.readFileSync(R+'/source/calibration.json','utf8')),axis=cal.commonAxis,t=axis.tangent,n=axis.normal;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),smooth=x=>{x=clamp(x);return x*x*(3-2*x)},dot=(a,b)=>a[0]*b[0]+a[1]*b[1];
const sourceTraces=[
{upper:[[215.5,227.5],[217,222.3],[220,217.8],[224,214.6],[229,213.3],[234.3,213.9],[238.7,216.8],[241.4,219.7],[243.4,222]],lower:[[215.5,227.5],[218.5,232],[223.2,235],[229.6,236.1],[235.5,235.3],[240.3,232.7],[243.2,227.8],[243.4,222]],sag:2.5,skew:-.12},
{upper:[[266,213.5],[266.8,209],[269.2,205.4],[273.4,202.3],[278.2,201],[283,201.6],[287.5,203.5],[290.9,205.8],[293.2,207.3]],lower:[[266,213.5],[268.7,218.8],[273.5,222.6],[279.1,224.1],[284.7,222.8],[289,219],[292,213.3],[293.2,207.3]],sag:2.7,skew:.08}
];
function interp(points,x){if(x<=points[0][0])return points[0][1];if(x>=points.at(-1)[0])return points.at(-1)[1];let i=0;while(points[i+1][0]<x)i++;const h=points[i+1][0]-points[i][0],u=(x-points[i][0])/h;const d=k=>(points[k+1][1]-points[k][1])/(points[k+1][0]-points[k][0]);const m=k=>{if(k===0)return d(0);if(k===points.length-1)return d(k-1);const a=d(k-1),b=d(k);if(a*b<=0)return 0;const h0=points[k][0]-points[k-1][0],h1=points[k+1][0]-points[k][0];return 3*(h0+h1)/((2*h1+h0)/a+(h1+2*h0)/b)};return (2*u**3-3*u*u+1)*points[i][1]+(u**3-2*u*u+u)*h*m(i)+(-2*u**3+3*u*u)*points[i+1][1]+(u**3-u*u)*h*m(i+1);}
const eyes=cal.eyes.map((e,i)=>{const a=e.left.xy,b=e.right.xy,uv=p=>[dot([p[0]-a[0],p[1]-a[1]],t),dot([p[0]-a[0],p[1]-a[1]],n)],p=sourceTraces[i];return {id:e.id,a,b,width:uv(b)[0],endV:uv(b)[1],upper:p.upper.map(uv),lower:p.lower.map(uv),contour:e.contour,sag:p.sag,skew:p.skew,toUV:uv};});
function point(e,u,v){return [e.a[0]+u*t[0]+v*n[0],e.a[1]+u*t[1]+v*n[1]]}
function paths(e,p,u){const f=clamp(u/e.width),ch=e.endV*f,h=Math.pow(Math.sin(Math.PI*f),1.1),closed=ch+e.sag*h*(1+e.skew*(2*f-1)),up=interp(e.upper,u),lo=interp(e.lower,u);
const uk=[[0,up],[.35,up+(closed-up)*.36],[.78,closed-(lo-up)*.08*h],[1,closed]];
const lk=[[0,lo],[.35,lo+(closed-lo)*.14],[.78,closed+(lo-up)*.11*h],[1,closed]];
return [interp(uk,p),interp(lk,p),up,lo,closed];}
function inside(x,y,p){let a=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const [xi,yi]=p[i],[xj,yj]=p[j];if((yi>y)!=(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)a=!a;}return a;}
function distance(x,y,p){let d=Infinity;for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],dx=b[0]-a[0],dy=b[1]-a[1],f=clamp(((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy));d=Math.min(d,Math.hypot(x-a[0]-f*dx,y-a[1]-f*dy));}return inside(x,y,p)?-d:d;}
const raw=b=>sharp(b,{raw:{width:W,height:W,channels:4}});
function sample(b,x,y,c){x=clamp(x-.5,0,511);y=clamp(y-.5,0,511);const ix=Math.floor(x),iy=Math.floor(y),dx=x-ix,dy=y-iy;return [0,1].reduce((s,k)=>s+[0,1].reduce((s,l)=>s+b[(Math.min(511,iy+k)*W+Math.min(511,ix+l))*4+c]*(l?dx:1-dx)*(k?dy:1-dy),0),0);}
(async()=>{
const source=fs.readFileSync(R+'/source/idle.alt.png'),base=await sharp(source).ensureAlpha().raw().toBuffer(),selected=[],indices=new Int8Array(N).fill(-1),mask=Buffer.alloc(N*4);
for(let y=193;y<241;y++)for(let x=209;x<299;x++){const j=y*W+x;for(let i=0;i<2;i++)if(distance(x+.5,y+.5,eyes[i].contour)<3.5){indices[j]=i;selected.push(j);mask[j*4]=mask[j*4+1]=mask[j*4+2]=mask[j*4+3]=255;break;}}
const plate=Float64Array.from(base);for(const j of selected)for(let c=0;c<3;c++)plate[j*4+c]=[235,183,151][c];
for(let k=0;k<2400;k++){let err=0;for(const j of selected)for(let c=0;c<3;c++){const val=(plate[(j-1)*4+c]+plate[(j+1)*4+c]+plate[(j-W)*4+c]+plate[(j+W)*4+c])/4;err=Math.max(err,Math.abs(val-plate[j*4+c]));plate[j*4+c]=val;}if(err<.0003)break;}
const clean=Buffer.from(base);for(const j of selected)for(let c=0;c<3;c++)clean[j*4+c]=Math.round(plate[j*4+c]);
await raw(clean).png().toFile(R+'/layers/face-clean.png');await raw(mask).png().toFile(R+'/layers/edit-mask.png');
const foreground=Buffer.from(base);for(const j of selected)foreground[j*4+3]=0;await raw(foreground).png().toFile(R+'/layers/protected-original.png');
for(let i=0;i<2;i++){const b=Buffer.alloc(N*4);for(const j of selected)if(indices[j]===i)base.copy(b,j*4,j*4,j*4+4);await raw(b).png().toFile(R+'/layers/eye-'+eyes[i].id+'-original.png');}
// Source-derived lash colour and soft cross-section. Its UV follows the BD-frame upper trace.
const inkTables=eyes.map(e=>Array.from({length:257},(_,k)=>{const u=e.width*(k+.5)/257,up=interp(e.upper,u),vals=[];for(let d=-1.3;d<=.2;d+=.25){const xy=point(e,u,up+d);vals.push([0,1,2].map(c=>sample(base,...xy,c)));}vals.sort((a,b)=>dot(a,[.3,.6])+.1*a[2]-(dot(b,[.3,.6])+.1*b[2]));return vals[1];}));
function color(ei,f){const v=clamp(f)*256,i=Math.floor(v),j=Math.min(i+1,256);return inkTables[ei][i].map((c,k)=>c*(1-v+i)+inkTables[ei][j][k]*(v-i));}
function ink(e,ei,p,u,v,up){const f=u/e.width;if(f<=0||f>=1)return [0,0,0,0];const du=.08,slope=(paths(e,p,Math.min(e.width,u+du))[0]-paths(e,p,Math.max(0,u-du))[0])/(Math.min(e.width,u+du)-Math.max(0,u-du)),normal=(v-up)/Math.sqrt(1+slope*slope),sigma=1.05*(1-p)+.56*p,taper=smooth(f/.05)*smooth((1-f)/.065),alpha=Math.exp(-.5*(normal/sigma)**2)*taper*.97;return [...color(ei,clamp(f,.08,.92)),alpha];}
function model(j,ei,p){const e=eyes[ei],ix=j%W,iy=Math.floor(j/W),rgb=[0,0,0],SS=3;
for(let sy=0;sy<SS;sy++)for(let sx=0;sx<SS;sx++){const [u,v]=e.toUV([ix+(sx+.5)/SS,iy+(sy+.5)/SS]),[up,lo]=paths(e,p,u),ap=u>=0&&u<=e.width&&p<1?clamp((v-up)*2+.5)*clamp((lo-v)*2+.5):0,c=ink(e,ei,p,u,v,up);for(let k=0;k<3;k++)rgb[k]+=((clean[j*4+k]*(1-ap)+base[j*4+k]*ap)*(1-c[3])+c[k]*c[3])/(SS*SS);}
return rgb;}
// Store only the open reconstruction residual. Fade this small local residual out as the lid leaves the source contour.
const residual=new Float32Array(N*3);for(const j of selected){const m=model(j,indices[j],0);for(let c=0;c<3;c++)residual[j*3+c]=base[j*4+c]-m[c];}
function render(p){if(p===0)return Buffer.from(base);const b=Buffer.from(base),r=1-smooth(p/.18);for(const j of selected){const c=model(j,indices[j],p);for(let k=0;k<3;k++)b[j*4+k]=Math.round(clamp(c[k]+r*residual[j*3+k],0,255));}return b;}
const states=[['open',0],['light',.35],['near',.78],['closed',1]],frames=[];
for(const [name,p]of states){const b=render(p);frames.push(b);if(!p)fs.copyFileSync(R+'/source/idle.alt.png',R+'/frames/'+name+'.png');else await raw(b).png().toFile(R+'/frames/'+name+'.png');}
for(const p of [.005,.015,.05,.12,.5,.65,.9,.97])await raw(render(p)).png().toFile(R+'/qa/p-'+p+'.png');
let outlines='<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><path d="M210,231.861 L301,205" stroke="#00d9ed" stroke-width=".22" fill="none"/>';
for(const e of eyes)for(const [name,p]of states){let d='';for(let k=0;k<=100;k++){const u=e.width*k/100;d+=(k?' L':'M')+point(e,u,paths(e,p,u)[0]);}outlines+='<path d="'+d+'" stroke="'+({open:'#67ffaa',light:'#ffee70',near:'#ee7fff',closed:'#00deff'}[name])+'" stroke-width=".25" fill="none"/>';}
outlines+='</svg>';fs.writeFileSync(R+'/qa/curves.svg',outlines);await sharp(source).composite([{input:Buffer.from(outlines)}]).png().toFile(R+'/qa/curves-on-source.png');
for(const bg of ['light','dark']){const comp=[],ec={left:207,top:190,width:94,height:54};for(let i=0;i<4;i++){const label=Buffer.from('<svg width="752" height="36"><text x="14" y="25" fill="'+(bg==='dark'?'white':'#243042')+'" font-size="20" font-family="Arial">'+states[i][0].toUpperCase()+' / BD axis</text></svg>');comp.push({input:label,left:i%2*752,top:Math.floor(i/2)*468});comp.push({input:await raw(frames[i]).extract(ec).resize(752,432).png().toBuffer(),left:i%2*752,top:Math.floor(i/2)*468+36});}await sharp({create:{width:1504,height:936,channels:4,background:bg==='dark'?'#202630':'#f2f0e9'}}).composite(comp).png().toFile(R+'/previews/eyes-'+bg+'.png');}
const spec={technique:'BD-local fixed-eye texture clipping with independently authored lids; source-derived lash colours; harmonic skin plate. Not a native Cubism file.',axis,eyes:eyes.map(({toUV,...e})=>e),closeKeyforms:[0,.35,.78,1],openResidualCorrectionRange:.18,sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),maskDerivation:'3.5 px exterior support around current source-only calibration envelope; new mask generated here',stateFiles:states.map(([name,p])=>({name,close:p,file:'frames/'+name+'.png'}))};fs.writeFileSync(R+'/rig.json',JSON.stringify(spec,null,2));
const report={frames:[],geometry:[],sourceSha256:spec.sourceSha256,editPixels:selected.length};for(let i=0;i<frames.length;i++){let outside=0,alpha=0,changed=0;for(let j=0;j<N;j++){if(frames[i][j*4+3]!==base[j*4+3])alpha++;if([0,1,2].some(c=>frames[i][j*4+c]!==base[j*4+c])){changed++;if(indices[j]<0)outside++;}}report.frames.push({state:states[i][0],outside,alpha,changed});}for(const e of eyes){let minGap=Infinity,nonmonotonic=0,last=Infinity;for(let pi=0;pi<=100;pi++){let area=0;for(let k=0;k<=100;k++){const [up,lo]=paths(e,pi/100,e.width*k/100);minGap=Math.min(minGap,lo-up);area+=lo-up;}if(area>last+.0001)nonmonotonic++;last=area;}report.geometry.push({eye:e.id,minGap,nonmonotonic,closedMidpoint:point(e,e.width/2,paths(e,1,e.width/2)[0])});}
fs.writeFileSync(R+'/qa/initial-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
if(process.argv.includes('--sequence')){fs.mkdirSync(R+'/frames/slider',{recursive:true});for(let k=0;k<=40;k++)await raw(render(k/40)).png().toFile(R+'/frames/slider/'+String(k).padStart(2,'0')+'.png');const seq=[{p:0,ms:1000}];for(let ms=0;ms<300;ms+=20){const p=ms<80?smooth((ms+10)/80):ms<140?1:1-smooth((ms-140+10)/160);seq.push({p,ms:20});}seq.push({p:0,ms:2700});const bufs=[];for(let i=0;i<seq.length;i++){const b=render(seq[i].p);seq[i].file='frames/sequence/'+String(i).padStart(2,'0')+'.png';await raw(b).png().toFile(R+'/'+seq[i].file);bufs.push(b);}fs.writeFileSync(R+'/timing.json',JSON.stringify({loopMs:4000,blinkMs:300,sequence:seq},null,2));for(const factor of[1,4]){const tag=factor===1?'normal':'slow',ani=()=>sharp(Buffer.concat(bufs),{raw:{width:512,height:512*bufs.length,channels:4,pageHeight:512}});await ani().webp({lossless:true,exact:true,delay:seq.map(s=>s.ms*factor),loop:0,effort:6}).toFile(R+'/previews/blink-'+tag+'.webp');await ani().flatten({background:'#f2f0e9'}).gif({delay:seq.map(s=>s.ms*factor),loop:0,dither:0,effort:7}).toFile(R+'/previews/blink-'+tag+'.gif');}}
})().catch(e=>{console.error(e);process.exitCode=1});
